// Generates .vitepress/sidebar.generated.js from the just-the-docs front
// matter already present in every page (title, nav_order, parent,
// has_children, nav_exclude). Navigation therefore stays defined by the
// markdown files themselves, exactly as it was under Jekyll.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const BOOK_DIRS = ['debug80-book', 'azm-book', 'glimmer-book'];

function frontMatter(filePath) {
  const text = readFileSync(filePath, 'utf8');
  const match = /^---\n([\s\S]*?)\n---/.exec(text);
  if (!match) return {};
  const fm = {};
  for (const line of match[1].split('\n')) {
    const kv = /^(\w+):\s*(.*)$/.exec(line);
    if (!kv) continue;
    fm[kv[1]] = kv[2].replace(/^["']|["']$/g, '');
  }
  return fm;
}

function mdFiles(dir) {
  return readdirSync(dir)
    .filter((name) => name.endsWith('.md'))
    .map((name) => join(dir, name));
}

function subDirs(dir) {
  return readdirSync(dir)
    .map((name) => join(dir, name))
    .filter((p) => statSync(p).isDirectory());
}

function pageLink(filePath) {
  const rel = relative(root, filePath).replace(/\\/g, '/');
  return `/${rel.replace(/\.md$/, '.html')}`;
}

function navOrder(fm) {
  const value = Number.parseFloat(fm.nav_order ?? '');
  return Number.isFinite(value) ? value : 9999;
}

function chapterItems(dir, parentTitle) {
  return mdFiles(dir)
    .filter((file) => !file.endsWith('index.md'))
    .map((file) => ({ file, fm: frontMatter(file) }))
    // `nav_exclude` pages still list under their `parent` section (the
    // just-the-docs has_toc pattern used by the MON-3 guide); it only hides
    // parentless pages.
    .filter(({ fm }) => fm.parent !== undefined || fm.nav_exclude !== 'true')
    .filter(({ fm }) => parentTitle === undefined || fm.parent === parentTitle)
    .sort((a, b) => navOrder(a.fm) - navOrder(b.fm))
    .map(({ file, fm }) => ({ text: fm.title ?? file, link: pageLink(file) }));
}

function bookSidebar(bookDir) {
  const sections = [];
  for (const dir of subDirs(bookDir)) {
    const indexPath = join(dir, 'index.md');
    let title;
    try {
      title = frontMatter(indexPath).title;
    } catch {
      continue;
    }
    const items = chapterItems(dir, title);
    if (items.length === 0) continue;
    sections.push({
      order: navOrder(frontMatter(indexPath)),
      entry: { text: title, collapsed: false, items },
    });
  }
  const rootItems = chapterItems(bookDir, undefined).map((item) => ({
    order: 0,
    entry: item,
  }));
  return [...rootItems, ...sections]
    .sort((a, b) => a.order - b.order)
    .map(({ entry }) => entry);
}

const sidebars = {};
for (const book of BOOK_DIRS) {
  sidebars[`/${book}/`] = bookSidebar(join(root, book));
}

const banner = '// Generated by generate-sidebar.mjs — do not edit by hand.\n';
writeFileSync(
  join(root, '.vitepress', 'sidebar.generated.js'),
  `${banner}export const sidebars = ${JSON.stringify(sidebars, null, 2)};\n`,
);
console.log(
  Object.entries(sidebars)
    .map(([key, value]) => `${key} ${value.length} sections`)
    .join('\n'),
);
